name: Veracode Golang Application

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      ref:
        required: true
        type: string
      token:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          token: ${{ inputs.token }}
      - name: Check if go.mod exists
        id: check-go-mod
        run: |
          if [ -f "go.mod" ]; then
            echo "go.mod exists"
            echo "::set-output name=go_mod_exists::true"
          else
            echo "go.mod does not exist"
            echo "::set-output name=go_mod_exists::false"
          fi

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.x

      - name: Install vcgopkg
        run: |
          export GOPATH=`go env GOPATH` &&
          export PATH="$GOPATH/bin:$PATH" && go install github.com/relaxnow/vcgopkg@latest

      - name: Initialize and tidy go mod
        run: |
          if [[ "${{ steps.check-go-mod.outputs.go_mod_exists }}" == "false" ]]; then
            go mod init github.com/${{ inputs.repository }}
            go mod tidy
          fi

      - name: Run vcgopkg
        run: vcgopkg
        
      - uses: actions/upload-artifact@v4
        with:
          name: veracode-artifact
          path: ./veracode
